express = require('express')
router = express.Router()
request = require('request')
url = require('url')
      

router.get '/*', (req, res, next) ->
  res.render 'index',
    title: 'A2N Chart'
module.exports = router

# ---
# generated by js2coffee 2.2.0