// Generated by CoffeeScript 1.8.0
(function() {
  var express, request, router, url;

  express = require('express');

  router = express.Router();

  request = require('request');

  url = require('url');

  router.get('/*', function(req, res, next) {
    return res.render('index', {
      title: 'A2N Chart'
    });
  });

  module.exports = router;

}).call(this);
